### PR TITLE
Add react router dom

### PR DESCRIPTION
**Pull request by Blakerc**

### CODE REVIEW

**Comment by Blakerc** [comment]
had this page open and not my forked :)

**Comment by SciathGH** [comment]
Im afraid we'll have to wait on @Peter-Crawley as they're the only ones who know web development to any degree

**Comment by Blakerc** [comment]
I'm a professional web developer. I am working on my own fork of this website which will be a full react app using typescript

**Comment by SciathGH** [comment]
Oh I see, I unfortunately am not professional, and the most professional member we have on our team is @Peter-Crawley they're also I think the only ones with merge perms to here, so again unfortunately you'll have to wait.
Ty for your work tho!

**Comment by Blakerc** [comment]
oh yeah I assumed! this PR was meant for my own fork so no worries :)

**Comment by SciathGH** [comment]
Oh I see!

**Pull request closed without merging**
