### PR TITLE
Add wiki button

### PR DESCRIPTION
**Pull request by trainb0y**
Also put the GitHub button above the Discord and Reddit buttons as otherwise it looked weird

### CODE REVIEW

**Comment by Peter-Crawley** [comment]
It was sorted in order of importance, that is why Discord was at the top.

I would prefer for it to be sorted like so:
- Discord
- Wiki
- GitHub
- Reddit

**Comment by trainb0y1** [comment]
image

I would argue that the wiki is more important. Also, separating the wiki and the github does *not* look good.

**Comment by trainb0y1** [comment]
> It was sorted in order of importance, that is why Discord was at the top.
> 
> I would prefer for it to be sorted like so:
> 
>     * Discord
> 
>     * Wiki
> 
>     * GitHub
> 
>     * Reddit

I do think that could look okay, give me a minute

**Comment by trainb0y1** [comment]
image
Alright, reordered to this

**Comment by trainb0y** [comment]
I completely forgot about this pr lmao

**Pull request closed without merging**
